import { expect, test, type Page } from "@playwright/test";

async function waitForMsw(page: Page) {
  await page.waitForFunction(
    () => (window as { __mswReady?: boolean }).__mswReady === true,
  );
}

async function bootstrapAuthenticatedSession(page: Page) {
  await page.addInitScript(() => {
    const bootstrapKey = "__e2e_bootstrapped__";
    if (!localStorage.getItem(bootstrapKey)) {
      localStorage.clear();
      localStorage.setItem(bootstrapKey, "1");
    }
    const session = {
      token: "e2e-token",
      user: {
        id: "u-1",
        name: "Mohamad",
        email: "mohamad@example.com",
        twoFAEnabled: false,
      },
    };
    localStorage.setItem("console-auth-session", JSON.stringify(session));
  });
}

test("login redirects to console successfully", async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.clear();
  });

  await page.goto("/login");
  await waitForMsw(page);

  await page.locator('input[name="email"]').fill("mohamad@example.com");
  await page.locator('input[name="password"]').fill("Password123!");
  await page.getByRole("button", { name: "Login" }).click();

  await expect(page).toHaveURL(/\/console$/, { timeout: 10_000 });
  await expect(page.getByText("Console Overview")).toBeVisible();
});

test("billing topup adds a payment record", async ({ page }) => {
  await bootstrapAuthenticatedSession(page);

  await page.goto("/console/billing/topup");
  await waitForMsw(page);

  await page.getByRole("spinbutton", { name: "Top-up amount" }).fill("120000");
  await page.getByRole("button", { name: "Submit top-up payment" }).click();
  await expect(page.getByText("Top-up completed successfully.")).toBeVisible();

  const runtimeState = await page.evaluate(() => {
    const raw = window.localStorage.getItem("mock-runtime-state");
    return raw ? JSON.parse(raw) : null;
  });
  const payments = runtimeState?.billingByAccountId?.["acc-1"]?.payments ?? [];
  expect(Array.isArray(payments)).toBeTruthy();
  expect(payments.length).toBeGreaterThan(0);
  expect(payments[0]?.amount).toBe(120000);

  await page.goto("/console/billing/payments");
  await expect(page).toHaveURL(/\/console\/billing\/payments/);
  await expect(page.getByText("Payment History")).toBeVisible();
});

test("creating a ticket redirects to ticket detail", async ({ page }) => {
  await bootstrapAuthenticatedSession(page);

  const subject = `E2E ticket ${Date.now()}`;
  await page.goto("/console/support/tickets/new");
  await waitForMsw(page);

  await page.getByLabel("Ticket subject").fill(subject);
  await page.getByLabel("Ticket description").fill(
    "Ticket body generated by Playwright E2E scenario.",
  );
  await page.getByRole("button", { name: "Submit ticket" }).click();

  await expect(page).toHaveURL(/\/console\/support\/tickets\/t-/);
  await expect(page.getByRole("heading", { name: subject })).toBeVisible();
});

test("settings table density persists after save and refresh", async ({ page }) => {
  await bootstrapAuthenticatedSession(page);

  await page.goto("/console/settings");
  await waitForMsw(page);
  await expect(page.getByText("Settings")).toBeVisible();

  const densitySelect = page.getByRole("combobox", { name: "Select table density" });
  await densitySelect.click();
  const listbox = page.getByRole("listbox");
  await expect(listbox).toBeVisible();
  await listbox.getByRole("option", { name: "Compact", exact: true }).click();
  await expect(densitySelect).toContainText(/compact/i);
  const saveButton = page.getByRole("button", { name: "Save settings changes" });
  await expect(saveButton).toBeEnabled();
  await saveButton.click();

  const prefsAfterSave = await page.evaluate(() => {
    const raw = window.localStorage.getItem("console-ui-preferences");
    return raw ? JSON.parse(raw) : null;
  });
  expect(prefsAfterSave?.tableDensity).toBe("compact");

  await page.reload();
  await expect(page.getByRole("combobox", { name: "Select table density" })).toContainText(/compact/i);
});
